-- Two journals that decouple "we received something" from "we acted on it".
--
-- Webhook deliveries from Bamboo and Bitbucket are retried a limited number of
-- times, so the controller must persist and return 200 fast. Outbound calls to
-- Trello and Telegram are rate limited and can fail, so they are queued rather
-- than issued inline. Both survive a container restart.

-- Raw inbound webhook deliveries, stored before any parsing.
CREATE TABLE inbound_event
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source          VARCHAR(32)  NOT NULL,
    external_id     VARCHAR(255) NOT NULL,
    event_type      VARCHAR(128) NOT NULL,
    payload         JSONB        NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_error      TEXT,
    received_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at    TIMESTAMPTZ,

    -- Redelivery of the same webhook must not produce a second row. This is the
    -- whole idempotency story on the inbound side.
    CONSTRAINT uq_inbound_event_source_external UNIQUE (source, external_id),
    CONSTRAINT ck_inbound_event_status CHECK (status IN ('PENDING', 'DONE', 'SKIPPED', 'FAILED'))
);

CREATE INDEX idx_inbound_event_claimable
    ON inbound_event (next_attempt_at, id)
    WHERE status = 'PENDING';

-- Queued calls to Trello and Telegram.
CREATE TABLE outbound_task
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target          VARCHAR(32)  NOT NULL,
    action          VARCHAR(64)  NOT NULL,
    dedup_key       VARCHAR(255) NOT NULL,
    payload         JSONB        NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_error      TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    completed_at    TIMESTAMPTZ,

    -- Guards against enqueueing the same message twice when an inbound event is
    -- processed more than once.
    CONSTRAINT uq_outbound_task_dedup_key UNIQUE (dedup_key),
    CONSTRAINT ck_outbound_task_status CHECK (status IN ('PENDING', 'DONE', 'SKIPPED', 'FAILED'))
);

CREATE INDEX idx_outbound_task_claimable
    ON outbound_task (next_attempt_at, id)
    WHERE status = 'PENDING';
