-- What we know about deployments, independent of how we found out (webhook or poll).
--
-- The unique constraint on the Bamboo result id is what makes the two ingestion
-- paths safe to run together and makes redelivery harmless: the same deployment
-- observed twice is one row and one notification.
CREATE TABLE deployment_record
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bamboo_deployment_result_id BIGINT       NOT NULL,
    project_name                VARCHAR(255) NOT NULL,
    environment_name            VARCHAR(255) NOT NULL,
    version_name                VARCHAR(255),
    status                      VARCHAR(32)  NOT NULL,
    started_at                  TIMESTAMPTZ,
    finished_at                 TIMESTAMPTZ,
    trigger_sentence            TEXT,
    recorded_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    notified_at                 TIMESTAMPTZ,

    CONSTRAINT uq_deployment_record_result UNIQUE (bamboo_deployment_result_id)
);

CREATE INDEX idx_deployment_record_environment
    ON deployment_record (environment_name, recorded_at DESC);
