-- Which Trello card mirrors which pull request.
--
-- Without this the service could only ever create cards, never move them: the
-- Bitbucket payload says nothing about Trello. The natural key is the pull
-- request itself, so no guessing from branch names is involved.
CREATE TABLE pr_card_link
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key     VARCHAR(64)  NOT NULL,
    repo_slug       VARCHAR(128) NOT NULL,
    pr_id           BIGINT       NOT NULL,
    trello_board_id VARCHAR(64)  NOT NULL,
    trello_card_id  VARCHAR(64),
    current_list_id VARCHAR(64),
    -- Filled in by the Jira enrichment phase; null when the branch carries no key.
    issue_key       VARCHAR(64),
    archived        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_pr_card_link UNIQUE (project_key, repo_slug, pr_id)
);
