-- Last observed state of each pull request, for the polling ingestion path.
--
-- Webhooks say what happened; polling only shows what things look like now, so the
-- event has to be recovered by comparing against the previous observation. That
-- previous observation has to survive restarts, hence a table rather than memory.
--
-- Separate from pr_card_link because the two answer different questions: this is
-- "what did Bitbucket last look like", that is "which card mirrors this PR". A
-- repository can be polled before it is ever mirrored, and a card outlives the
-- polling of it.
CREATE TABLE pr_poll_state
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_key   VARCHAR(64)  NOT NULL,
    repo_slug     VARCHAR(128) NOT NULL,
    pr_id         BIGINT       NOT NULL,

    -- OPEN / MERGED / DECLINED. The main driver of lifecycle transitions.
    state         VARCHAR(32)  NOT NULL,
    -- Bitbucket bumps this on any edit; cheap way to notice title/description changes.
    version       INTEGER,
    -- Head of the source branch: a change means new commits were pushed.
    latest_commit VARCHAR(64),
    -- Digest of the reviewer approval set, so an approval is visible as a change
    -- without storing the whole reviewer list.
    reviewer_digest VARCHAR(64),

    first_seen_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_pr_poll_state UNIQUE (project_key, repo_slug, pr_id)
);
